version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "DEPS"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "DEPS"
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    groups:
      gems:
        patterns:
          - "*"
