inherit_gem:
  rubocop-discourse-base:
    - stree-compat.yml
    - rubocop-rspec.yml

AllCops:
  TargetRubyVersion: "3.4"
  NewCops: enable

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true
  IgnoreNotImplementedMethods: true

RSpec/DescribeClass:
  Exclude:
    - spec/docs/**/*
    - spec/integration/**/*
    - spec/system/**/*
